version: "3.9"

redis:
  image: redis:6
  container_name: message_service_local_redis

services:
  mailing_service:
    restart: always
    build: 
      context: ./
    ports: 
      - "8000:8000"
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]



  